services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db_for_chatApp
    environment:
      POSTGRES_USER: vladok
      POSTGRES_PASSWORD: mytestdbpass1
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vladok -d main"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
