'use strict';

const MessageType = {
  USER_LOGIN: 'USER_LOGIN',
  ROOM_JOIN: 'ROOM_JOIN',
  MESSAGE_SEND: 'MESSAGE_SEND',
  MESSAGE_NEW: 'MESSAGE_NEW',
  ERROR: 'ERROR',
  ROOM_CREATE: 'ROOM_CREATE',
  ROOM_NEW: 'ROOM_NEW',
  ROOM_RENAME: 'ROOM_RENAME',
  ROOM_RENAMED: 'ROOM_RENAMED',
  ROOM_DELETE: 'ROOM_DELETE',
  ROOM_DELETED: 'ROOM_DELETED',
};

module.exports = { MessageType };
